import Head from 'next/head';
import Layout from '../components/Layout';
import { Hero, Logo, Phrase, Vision } from '../sections';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Hero />
        <Logo />
        <Phrase />
        <Vision />
      </Layout>
    </>
  );
}
